# Generated by Django 5.0.2 on 2024-02-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=200)),
                ("definition", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbr", models.CharField(max_length=5)),
                ("term", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("COM", "Common"), ("PROP", "Proper nouns")],
                        max_length=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GR", "Grammar"),
                            ("CO", "Content"),
                            ("SO", "Source"),
                            ("WL", "Word list"),
                        ],
                        max_length=200,
                    ),
                ),
                ("definition", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TxtSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lemma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cf", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("components", models.ManyToManyField(blank=True, to="emedict.lemma")),
                (
                    "pos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.pos"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cf", models.CharField(blank=True, max_length=200)),
                ("formtype", models.ManyToManyField(blank=True, to="emedict.formtype")),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LemmaDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LemmaOid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(blank=True, max_length=20)),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spelling_lat", models.CharField(max_length=200)),
                ("spelling_cun", models.CharField(blank=True, max_length=200)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.form"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LemmaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.TextField(blank=True)),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.tag"
                    ),
                ),
                (
                    "tagsource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emedict.txtsource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lemma",
            name="tags",
            field=models.ManyToManyField(through="emedict.LemmaTag", to="emedict.tag"),
        ),
        migrations.CreateModel(
            name="LemmaCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.CharField(max_length=1000)),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emedict.txtsource",
                    ),
                ),
            ],
        ),
    ]
