# Generated by Django 5.0.1 on 2024-02-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lemma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.IntegerField(default=None)),
                ("cf", models.CharField(max_length=200)),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("V", "Verb"),
                            ("N", "Noun"),
                            ("ADJ", "Adjective"),
                            ("O", "Other"),
                        ],
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LemmaDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LemmaSpelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spelling_lat", models.CharField(max_length=200)),
                ("spelling_cun", models.CharField(default="", max_length=200)),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LemmaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.TextField()),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.tag"
                    ),
                ),
            ],
        ),
    ]
