# Generated by Django 5.0.1 on 2024-02-03 19:23

from django.db import migrations

import json
import re

def add_data(apps, schema_editor):
    datapath = "emedict/migrations/data/gloss-sux.json"

    posdict = {
        "N": "N",
        "V/t": "V",
        "V/i": "V",
        "AJ": "ADJ",    
        "CNJ": "CNJ"
    }

    Lemma = apps.get_model("emedict", "Lemma")
    LemmaDef = apps.get_model("emedict", "LemmaDef")
    LemmaSpelling = apps.get_model("emedict", "LemmaSpelling")

    with open(datapath, "r", encoding="utf8") as infile:
        data = json.load(infile)["entries"]

    for l in data:
        oid = int(l["oid"][1:])

        if Lemma.objects.filter(oid=oid):
            continue

        newl = Lemma(
            oid=int(l["oid"][1:]),
            cf=l["cf"],
            pos=posdict.get(l["pos"], "O")
        )

        newl.save()

        for sense in l["senses"]:
            s = sense["mng"]
            newd = LemmaDef(
                lemma=newl,
                definition=s
            )
            newd.save()

        for base in l["bases"]:
            b = base["n"]
            b = re.sub(r"%sux:", "", b) 

            newb = LemmaSpelling(
                lemma=newl,
                spelling_lat=b
            )

            newb.save()


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]