# Generated by Django 5.0.2 on 2024-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='status',
            field=models.CharField(choices=[('NR', 'not reviewd'), ('R', 'reviewed'), ('RD', 'reviewed and documented')], default='NR', max_length=5),
        ),
        migrations.AddField(
            model_name='txtsource',
            name='abbr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='txtsource',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='tags',
            field=models.ManyToManyField(blank=True, through='emedict.LemmaTag', to='emedict.tag'),
        ),
        migrations.AlterField(
            model_name='txtsource',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
