# Generated by Django 5.0.1 on 2024-02-19 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0002_auto_20240203_1923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lemmatag",
            name="tagsource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emedict.txtsource",
            ),
        ),
    ]
