# Generated by Django 5.0.2 on 2024-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0003_auto_20240225_2020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lemma",
            name="tags",
            field=models.ManyToManyField(
                blank=True, through="emedict.LemmaTag", to="emedict.tag"
            ),
        ),
    ]
