# Generated by Django 5.0.2 on 2024-02-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0003_contenttag_grammartag_alter_lemma_pos_lemmactag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttag',
            name='definition',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grammartag',
            name='definition',
            field=models.TextField(default=''),
        ),
    ]
