# Generated by Django 5.0.2 on 2024-02-27 14:21

from django.db import migrations
import json

def load_data(datapath: str = "emedict/migrations/data/gloss-sux.json") -> list[dict]:
    with open(datapath, "r", encoding="utf8") as infile:
        data = json.load(infile)["entries"]

    return data

def add_data(apps, schema_editor):
    Lemma = apps.get_model("emedict", "Lemma")
    data = load_data()
    
    for parent in data:
        if (parent.get("compound", None) and parent.get("oid", None)):
            try:
                parentl = Lemma.objects.get(lemmaoid__oid=parent["oid"])
                comp_oids = [c["ref"] for c in parent["compound"]]
                for compoid in comp_oids:
                    compl = Lemma.objects.get(lemmaoid__oid=compoid)
                    parentl.components.add(compl)
            except:
                print(f"No lemma {parent['oid']}")

class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0003_auto_20240227_1417'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
