# Generated by Django 5.0.1 on 2024-02-20 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0003_alter_lemmatag_tagsource"),
    ]

    operations = [
        migrations.CreateModel(
            name="LemmaOid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(blank=True, max_length=20)),
                (
                    "lemma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emedict.lemma"
                    ),
                ),
            ],
        ),
    ]
