# Generated by Django 5.0.2 on 2024-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0004_alter_lemma_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="lemma",
            name="status",
            field=models.CharField(
                choices=[
                    ("NR", "not reviewd"),
                    ("R", "reviewed"),
                    ("RD", "reviewed and documented"),
                ],
                default="NR",
                max_length=5,
            ),
        ),
    ]
