# Generated by Django 5.0.1 on 2024-02-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0004_lemmaoid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lemma",
            name="oid",
        ),
    ]
