# Generated by Django 5.0.2 on 2024-02-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0004_auto_20240227_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='sortform',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emedict.pos'),
        ),
    ]
