# Generated by Django 5.0.2 on 2024-02-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0004_alter_contenttag_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='contenttags',
            field=models.ManyToManyField(through='emedict.LemmaCTag', to='emedict.contenttag'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='grammartags',
            field=models.ManyToManyField(through='emedict.LemmaGTag', to='emedict.grammartag'),
        ),
    ]
