# Generated by Django 5.0.2 on 2024-02-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0005_lemma_sortform_alter_lemma_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='sortform',
            field=models.CharField(max_length=200),
        ),
    ]
