# Generated by Django 5.0.2 on 2024-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0005_lemma_contenttags_lemma_grammartags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttag',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grammartag',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lemmactag',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lemmagtag',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lemmaspelling',
            name='spelling_cun',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
