# Generated by Django 5.0.1 on 2024-02-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0006_lemma_components"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lemma",
            name="components",
            field=models.ManyToManyField(blank=True, to="emedict.lemma"),
        ),
    ]
