# Generated by Django 5.0.2 on 2024-02-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0006_alter_contenttag_definition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('GR', 'Grammar'), ('CO', 'Content')], max_length=200)),
                ('definition', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lemmactag',
            name='citation',
        ),
        migrations.CreateModel(
            name='LemmaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField(blank=True)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emedict.lemma')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emedict.tag')),
            ],
        ),
    ]
