# Generated by Django 5.0.2 on 2024-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedict', '0007_tag_remove_lemmactag_citation_lemmatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='tags',
            field=models.ManyToManyField(through='emedict.LemmaTag', to='emedict.tag'),
        ),
    ]
