# Generated by Django 5.0.2 on 2024-02-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emedict", "0008_auto_20240224_1734"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lemmacitation",
            name="source",
        ),
        migrations.AddField(
            model_name="lemmacitation",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="emedict.txtsource",
            ),
        ),
    ]
